<a href="https://colab.research.google.com/github/manisha02710/FDS-EXPERIMENT/blob/main/Ex10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create an array
array = np.array([83, 25, 19, 47, 62, 15, 96, 39, 51])

print("Original Array:")
print(array)

# Square root of array elements
print("\nSquare Root:")
print(np.sqrt(array))

# Check dimensions
print("\nDimension of Array:")
print(array.ndim)

# Reshape array into 3x3
new_array = array.reshape(3, 3)

print("\nReshaped Array:")
print(new_array)

# Check dimensions after reshaping
print("\nDimension after Reshaping:")
print(new_array.ndim)

# Convert 2D array back to 1D
print("\nRavelled Array:")
print(new_array.ravel())

# Array slicing
print("\nSelected Elements:")
print(new_array[2, 1:3])


Original Array:
[83 25 19 47 62 15 96 39 51]

Square Root:
[9.11043358 5.         4.35889894 6.8556546  7.87400787 3.87298335
 9.79795897 6.244998   7.14142843]

Dimension of Array:
1

Reshaped Array:
[[83 25 19]
 [47 62 15]
 [96 39 51]]

Dimension after Reshaping:
2

Ravelled Array:
[83 25 19 47 62 15 96 39 51]

Selected Elements:
[39 51]
